version: 0.2

env:
  parameter-store:
    DOCKER_HUB_USERNAME: "docker-hub-username"
    DOCKER_HUB_PASSWORD: "docker-hub-password"
    GITHUB_USERNAME: "agonyforge-github-packages-username"
    GITHUB_TOKEN: "agonyforge-github-packages-token"

phases:
  install:
    commands:
      - chmod +x ./gradlew
  pre_build:
    commands:
      - export CORE_VERSION=v`egrep "^version" agonyforge-mud-core/build.gradle | cut -f2 -d\'`
      - export MODELS_DYNAMODB_VERSION=v`egrep "^version" agonyforge-mud-models-dynamodb/build.gradle | cut -f2 -d\'`
      - export BRANCH_TAG=`echo ${CODEBUILD_SOURCE_VERSION} | sed 's|/|-|g'`
      - echo "Codebuild initiator is ${CODEBUILD_INITIATOR}"
      - echo "Branch is ${BRANCH_TAG}"
      - echo "Core version is ${CORE_VERSION}"
      - echo "Models DynamoDB version is ${MODELS_DYNAMODB_VERSION}"
  build:
    commands:
      - ./gradlew clean
      - ./gradlew :agonyforge-mud-core:build -x docker
      - ./gradlew :agonyforge-mud-models-dynamodb:build -x docker
  post_build:
    commands:
      - |
        if expr "${CODEBUILD_INITIATOR}" : "codepipeline*" >/dev/null; then                
          ./gradlew :agonyforge-mud-core:publish
          ./gradlew :agonyforge-mud-models-dynamodb:publish
        fi
