FROM amazoncorretto:17-alpine-jdk
LABEL maintainer="scion@agonyforge.com"
EXPOSE 8080
COPY agonyforge-mud-demo-*.jar /opt/app/mud.jar
WORKDIR /opt/app
CMD ["/usr/bin/java", \
"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", \
 "-jar", "mud.jar"]
